/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.FormatoCDTO;
import cliente.ClienteDeObjetos;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanf
 */
public class GUICoordinador extends javax.swing.JFrame {

    GUIInicioSesion objGuiInicioSesion;
    ClienteDeObjetos atrCO;

    /**
     * Creates new form GUICordinador
     */
    public GUICoordinador() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public GUICoordinador(GUIInicioSesion prmGUI) {
        initComponents();
        objGuiInicioSesion = prmGUI;
        this.setLocationRelativeTo(null);
        mostrarAnteproyectos();
    }

    public void mostrarAnteproyectos() {
        try {
            List<FormatoCDTO> listaAnteproyectos;
            this.setVisible(true);
            atrCO = ClienteDeObjetos.getInstancia();
            listaAnteproyectos = atrCO.getObjRemotoAnteproyectos().consultarFormatoC();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Codigo Anteproyecto");
            modelo.addColumn("Concepto 1");
            modelo.addColumn("Concepto 2");
            modelo.addColumn("Observaciones");

            tblAnteproyectos.setEnabled(false);
            for (int i = 0; i < listaAnteproyectos.size(); i++) {
                FormatoCDTO Formato = listaAnteproyectos.get(i);
                Object[] obj = new Object[]{Formato.getCodigoAnteproyecto(), Formato.getConcepto1(), Formato.getConcepto2(), Formato.getObservaciones()};
                modelo.addRow(obj);
            }

            tblAnteproyectos.setModel(modelo);
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlFondo = new javax.swing.JPanel();
        lblListado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAnteproyectos = new javax.swing.JTable();
        llblFondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        menuAsignar = new javax.swing.JMenu();
        menuCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("COORDINADOR");
        setIconImage(getIconImage());

        pnlFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblListado.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblListado.setText("Listado de anteproyectos");
        pnlFondo.add(lblListado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        tblAnteproyectos.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        tblAnteproyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Anteproyecto", "Titulo Anteproyecto", "Estudiante 1", "Estudiante 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAnteproyectos);

        pnlFondo.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 436, 250));

        llblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoCoordinado.png"))); // NOI18N
        pnlFondo.add(llblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 350));

        jMenuBar1.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        menuRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/registrarFormato.png"))); // NOI18N
        menuRegistrar.setText("Registrar Formato TI-D");
        menuRegistrar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        menuRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRegistrar);

        menuAsignar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/asignarEvaluadores.png"))); // NOI18N
        menuAsignar.setText("Asignar Evaluadores");
        menuAsignar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        menuAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAsignarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAsignar);

        menuCerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/cerrarS.png"))); // NOI18N
        menuCerrar.setText("Cerrar Sesion");
        menuCerrar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        menuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistrarMouseClicked
        new GUIRegistrarFD(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuRegistrarMouseClicked

    private void menuCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarMouseClicked
        this.dispose();
        objGuiInicioSesion.setVisible(true);
    }//GEN-LAST:event_menuCerrarMouseClicked

    private void menuAsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAsignarMouseClicked
        new GUIAsignarEvaluadores(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuAsignarMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblListado;
    private javax.swing.JLabel llblFondo;
    private javax.swing.JMenu menuAsignar;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JPanel pnlFondo;
    private javax.swing.JTable tblAnteproyectos;
    // End of variables declaration//GEN-END:variables
}
