/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import cliente.ClienteDeObjetos;
import java.awt.Image;
import java.awt.Toolkit;
import java.rmi.RemoteException;

/**
 *
 * @author Laura
 */
public class GUIConectarCliente extends javax.swing.JFrame {
    ClienteDeObjetos atrCO;
    static GUIConectarCliente vistaCliente;
    /**
     * Creates new form GUIConectarCliente
     */
    public GUIConectarCliente() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloCnxC = new javax.swing.JLabel();
        lblDireccionIpclnt = new javax.swing.JLabel();
        txtDireccionIpclnt = new javax.swing.JTextField();
        lblPuertoclnt = new javax.swing.JLabel();
        txtPuertoclnt = new javax.swing.JTextField();
        btnConectarC = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONECTAR CLIENTE");
        setIconImage(getIconImage());

        jPanel1.setPreferredSize(new java.awt.Dimension(425, 341));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCnxC.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblTituloCnxC.setForeground(new java.awt.Color(204, 204, 204));
        lblTituloCnxC.setText("Conexion Cliente");
        jPanel1.add(lblTituloCnxC, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, -1, -1));

        lblDireccionIpclnt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblDireccionIpclnt.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionIpclnt.setText("Cual es el la dirección ip donde se encuentra  el n_s");
        jPanel1.add(lblDireccionIpclnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, -1));

        txtDireccionIpclnt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDireccionIpclnt.setText("localhost");
        jPanel1.add(txtDireccionIpclnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 227, -1));

        lblPuertoclnt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPuertoclnt.setForeground(new java.awt.Color(255, 255, 255));
        lblPuertoclnt.setText("Cual es el número de puerto por el cual escucha el n_s");
        jPanel1.add(lblPuertoclnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, -1, -1));

        txtPuertoclnt.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPuertoclnt.setText("2021");
        jPanel1.add(txtPuertoclnt, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 228, -1));

        btnConectarC.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnConectarC.setText("Conectar");
        btnConectarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarCActionPerformed(evt);
            }
        });
        jPanel1.add(btnConectarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarCActionPerformed
        String IP = txtDireccionIpclnt.getText();
        int puerto = Integer.parseInt(txtPuertoclnt.getText());
        try {
            atrCO=ClienteDeObjetos.getInstancia();
            atrCO.setDireccionNS(IP);
            atrCO.setNumPuertoNS(puerto);
            atrCO.conectar();
            this.dispose();
            GUIInicioSesion objInicioSesion= new GUIInicioSesion();
            objInicioSesion.setVisible(true);
        } catch (RemoteException ex) {
            System.err.println("No fue posible Arrancar el NS o Registrar el objeto remoto" + ex.getMessage());
        }
    }//GEN-LAST:event_btnConectarCActionPerformed
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/iconApp.png"));
        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIConectarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIConectarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIConectarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIConectarCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vistaCliente= new GUIConectarCliente();
                vistaCliente.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarC;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDireccionIpclnt;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPuertoclnt;
    private javax.swing.JLabel lblTituloCnxC;
    private javax.swing.JTextField txtDireccionIpclnt;
    private javax.swing.JTextField txtPuertoclnt;
    // End of variables declaration//GEN-END:variables
}
