/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.FormatoADTO;
import SGestionAnteproyectos.dto.FormatoCDTO;
import cliente.ClienteDeObjetos;
import java.rmi.RemoteException;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author juanf
 */
public class GUICoordinador extends javax.swing.JFrame {

    GUIInicioSesion objGuiInicioSesion;
    ClienteDeObjetos atrCO;

    /**
     * Creates new form GUICordinador
     */
    public GUICoordinador() {
        initComponents();
    }

    public GUICoordinador(GUIInicioSesion prmGUI) {
        initComponents();
        objGuiInicioSesion = prmGUI;
        mostrarAnteproyectos();
    }

    public void mostrarAnteproyectos() {
        try {
            List<FormatoCDTO> listaAnteproyectos;
            this.setVisible(true);
            atrCO = ClienteDeObjetos.getInstancia();
            listaAnteproyectos = atrCO.getObjRemotoAnteproyectos().consultarFormatoC();
            DefaultTableModel modelo = new DefaultTableModel();
            modelo.addColumn("Codigo Anteproyecto");
            modelo.addColumn("Concepto 1");
            modelo.addColumn("Concepto 2");
            modelo.addColumn("Observaciones");

            tblAnteproyectos.setEnabled(false);
            for (int i = 0; i < listaAnteproyectos.size(); i++) {
                FormatoCDTO Formato = listaAnteproyectos.get(i);
                Object[] obj = new Object[]{Formato.getCodigoAnteproyecto(), Formato.getConcepto1(), Formato.getConcepto2(), Formato.getObservaciones()};
                modelo.addRow(obj);
            }

            tblAnteproyectos.setModel(modelo);
        } catch (Exception e) {
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblAnteproyectos = new javax.swing.JTable();
        lblListado = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuRegistrar = new javax.swing.JMenu();
        menuAsignar = new javax.swing.JMenu();
        menuCerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());

        tblAnteproyectos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo Anteproyecto", "Titulo Anteproyecto", "Estudiante 1", "Estudiante 2"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblAnteproyectos);

        lblListado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblListado.setText("Listado de anteproyectos");

        menuRegistrar.setText("Registrar Formato TI-D");
        menuRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuRegistrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuRegistrar);

        menuAsignar.setText("Asignar Evaluadores");
        menuAsignar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuAsignarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuAsignar);

        menuCerrar.setText("Cerrar Sesion");
        menuCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCerrarMouseClicked(evt);
            }
        });
        jMenuBar1.add(menuCerrar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(lblListado)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblListado)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuRegistrarMouseClicked
        new GUIRegistrarFD(this).setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_menuRegistrarMouseClicked

    private void menuCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCerrarMouseClicked
        this.dispose();
        objGuiInicioSesion.setVisible(true);
    }//GEN-LAST:event_menuCerrarMouseClicked

    private void menuAsignarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuAsignarMouseClicked
      new GUIAsignarEvaluadores(this).setVisible(true);
      this.setVisible(false);
    }//GEN-LAST:event_menuAsignarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUICoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUICoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUICoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUICoordinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUICoordinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblListado;
    private javax.swing.JMenu menuAsignar;
    private javax.swing.JMenu menuCerrar;
    private javax.swing.JMenu menuRegistrar;
    private javax.swing.JTable tblAnteproyectos;
    // End of variables declaration//GEN-END:variables
}
