/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.FormatoBDTO;
import cliente.ClienteDeObjetos;
import java.awt.Image;
import java.awt.Toolkit;
import java.rmi.RemoteException;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author juanf
 */
public class GUIFB extends javax.swing.JFrame {

    GUIEvaluador atrGUIEvaluador;
    List<FormatoBDTO> listFB;
    ClienteDeObjetos atrCO;
    FormatoBDTO atrFormatoSeleccionado;

    /**
     * Creates new form GUIFB
     */
    public GUIFB() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    public GUIFB(GUIEvaluador prmGUIEvaluador, List<FormatoBDTO> prmFB) {
        initComponents();
         this.setLocationRelativeTo(null);
        listFB = prmFB;
        atrGUIEvaluador = prmGUIEvaluador;
        buttonGroup1.add(rbAprobado);
        buttonGroup1.add(rbNoAprobado);
        txtIdEvaluador.setEnabled(false);
        for (FormatoBDTO formatoB : prmFB) {
            cmbCodigoAnteproyecto.addItem(String.valueOf(formatoB.getCodigoAnteproyecto()));
        }
        btnGuardar.setEnabled(false);
        cmbCodigoAnteproyecto.setSelectedIndex(0);
        cmbCodigoAnteproyecto.setEnabled(true);

    }

    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/iconApp.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnVolver = new javax.swing.JButton();
        mainPanel = new javax.swing.JPanel();
        btnGuardar = new javax.swing.JButton();
        rbAprobado = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        rbNoAprobado = new javax.swing.JRadioButton();
        lblIdEvaluador = new javax.swing.JLabel();
        txtCodigoAnteproyecto1 = new javax.swing.JTextField();
        txtIdEvaluador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        lblRegistrarForatoB = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCodigoAnteproyecto = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRAR FORMATO B");
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnVolver.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/back.png"))); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 110, 40));

        mainPanel.setBackground(new java.awt.Color(204, 204, 204));

        btnGuardar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        rbAprobado.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        rbAprobado.setText("Aprobado");

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel3.setText("Concepto:");

        rbNoAprobado.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        rbNoAprobado.setText("No Aprobado");

        lblIdEvaluador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblIdEvaluador.setText("Id Evaluador:");

        txtCodigoAnteproyecto1.setEditable(false);

        txtIdEvaluador.setEditable(false);
        txtIdEvaluador.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel4.setText("Observaciones");

        txtObservaciones.setColumns(20);
        txtObservaciones.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(56, 56, 56)
                                .addComponent(rbAprobado)
                                .addGap(18, 18, 18)
                                .addComponent(rbNoAprobado)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(lblIdEvaluador)
                                .addGap(38, 38, 38)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtIdEvaluador)))))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnGuardar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(122, 122, 122)
                    .addComponent(txtCodigoAnteproyecto1, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                    .addGap(22, 22, 22)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rbAprobado)
                    .addComponent(rbNoAprobado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdEvaluador)
                    .addComponent(txtIdEvaluador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addContainerGap())
            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(mainPanelLayout.createSequentialGroup()
                    .addGap(62, 62, 62)
                    .addComponent(txtCodigoAnteproyecto1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(237, Short.MAX_VALUE)))
        );

        jPanel1.add(mainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        lblRegistrarForatoB.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        lblRegistrarForatoB.setForeground(new java.awt.Color(255, 255, 255));
        lblRegistrarForatoB.setText("Registrar Formato B");
        jPanel1.add(lblRegistrarForatoB, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Codigo Anteproyecto: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        cmbCodigoAnteproyecto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        cmbCodigoAnteproyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "seleccionar Anteproyecto" }));
        jPanel1.add(cmbCodigoAnteproyecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, -1));

        btnBuscar.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/lupaBuscar.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(btnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 110, 40));

        lblFondo.setBackground(new java.awt.Color(102, 102, 102));
        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoB.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 4, 420, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 428, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (cmbCodigoAnteproyecto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un AnteProyecto", "INFO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            FormatoBDTO objFormato = listFB.get(cmbCodigoAnteproyecto.getSelectedIndex() - 1);
            if (rbAprobado.isSelected()) {
                objFormato.setAtrConcepto("APROBADO");
            } else {
                objFormato.setAtrConcepto("NO APROBADO");
            }
            Date date = new Date();
            objFormato.setFechaEvaluacion(date);
            objFormato.setObservaciones(txtObservaciones.getText());
            try {
                atrCO = ClienteDeObjetos.getInstancia();
                if (atrCO.getObjRemotoAnteproyectos().registrarFormatoB(objFormato)) {
                    JOptionPane.showMessageDialog(this, "Formato registrado Correctamente", "INFO", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    atrGUIEvaluador.cargarFormatos();
                    atrGUIEvaluador.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el Formato", "INFO", JOptionPane.INFORMATION_MESSAGE);
                }
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        System.out.println("index:" + cmbCodigoAnteproyecto.getSelectedIndex());
        if (cmbCodigoAnteproyecto.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Debe seleccionar un AnteProyecto", "INFO", JOptionPane.INFORMATION_MESSAGE);
        } else {
            try {
                btnGuardar.setEnabled(true);
                atrCO = ClienteDeObjetos.getInstancia();
                atrFormatoSeleccionado = listFB.get(cmbCodigoAnteproyecto.getSelectedIndex() - 1);
                System.out.println(atrFormatoSeleccionado.getIdEvaluador());
                txtIdEvaluador.setText(String.valueOf(atrFormatoSeleccionado.getIdEvaluador()));

                cmbCodigoAnteproyecto.setEnabled(false);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        this.dispose();
        atrGUIEvaluador.setVisible(true);
        atrGUIEvaluador.cargarFormatos();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFB.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFB().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCodigoAnteproyecto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIdEvaluador;
    private javax.swing.JLabel lblRegistrarForatoB;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rbAprobado;
    private javax.swing.JRadioButton rbNoAprobado;
    private javax.swing.JTextField txtCodigoAnteproyecto1;
    private javax.swing.JTextField txtIdEvaluador;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
