/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.FormatoBDTO;
import SGestionAnteproyectos.dto.FormatoCDTO;
import cliente.ClienteDeObjetos;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author juanf
 */
public class GUIFC extends javax.swing.JFrame {

    GUIJefeDepto atrGuiJefe;
    List<FormatoBDTO> atrList;
    FormatoBDTO atrFormatoSeleccionado;
    ClienteDeObjetos atrCO;

    /**
     * Creates new form GUIFC
     */
    public GUIFC() {
        initComponents();
    }

    public GUIFC(GUIJefeDepto prmGui, List<FormatoBDTO> prmList) {
        initComponents();
        buttonGroup.add(rbCorrecta);
        buttonGroup.add(rbIncorecta);
        buttonGroup1.add(rbAprobado3);
        buttonGroup1.add(rbNoAprobado3);
        atrGuiJefe = prmGui;
        atrList = prmList;
        // mainPanel.setVisible(false);
        cmbCodigoAnteproyecto.setEnabled(true);
        cargarFormatos();
    }

    public void cargarFormatos() {
        for (FormatoBDTO formatoB : atrList) {
            cmbCodigoAnteproyecto.addItem(String.valueOf(formatoB.getCodigoAnteproyecto()));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        lblRegistrarFormatoC = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();
        rbAprobado1 = new javax.swing.JRadioButton();
        rbNoAprobado1 = new javax.swing.JRadioButton();
        lblConcepto1 = new javax.swing.JLabel();
        lblConcepto2 = new javax.swing.JLabel();
        rbAprobado2 = new javax.swing.JRadioButton();
        rbNoAprobado2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbCorrecta = new javax.swing.JRadioButton();
        rbIncorecta = new javax.swing.JRadioButton();
        lblConcepto3 = new javax.swing.JLabel();
        rbAprobado3 = new javax.swing.JRadioButton();
        rbNoAprobado3 = new javax.swing.JRadioButton();
        lblObservaciones = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtObservaciones = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();
        cmbCodigoAnteproyecto = new javax.swing.JComboBox<>();
        lblCodigoAnteproyecto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRegistrarFormatoC.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRegistrarFormatoC.setText("Registrar Formato C");

        rbAprobado1.setSelected(true);
        rbAprobado1.setText("Aprobado");
        rbAprobado1.setEnabled(false);

        rbNoAprobado1.setText("No Aprobado");
        rbNoAprobado1.setEnabled(false);

        lblConcepto1.setText("Concepto 1:");

        lblConcepto2.setText("Concepto 2:");

        rbAprobado2.setSelected(true);
        rbAprobado2.setText("Aprobado");
        rbAprobado2.setEnabled(false);

        rbNoAprobado2.setText("No Aprobado");
        rbNoAprobado2.setEnabled(false);

        jLabel2.setText("Estructura: ");

        rbCorrecta.setText("Correcta");

        rbIncorecta.setSelected(true);
        rbIncorecta.setText("Incorrecta");

        lblConcepto3.setText("Concepto Departamento:");

        rbAprobado3.setText("Aprobado");

        rbNoAprobado3.setSelected(true);
        rbNoAprobado3.setText("No Aprobado");

        lblObservaciones.setText("Observaciones");

        txtObservaciones.setColumns(20);
        txtObservaciones.setRows(5);
        jScrollPane1.setViewportView(txtObservaciones);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lblConcepto2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addComponent(lblConcepto1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbNoAprobado1)
                        .addContainerGap())))
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel2)
                        .addGap(83, 83, 83))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblConcepto3)))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(rbAprobado1)
                                .addComponent(rbAprobado2)
                                .addComponent(rbCorrecta))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(rbIncorecta)
                                .addComponent(rbNoAprobado2))
                            .addContainerGap())
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(rbAprobado3)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(rbNoAprobado3)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblObservaciones)
                .addGap(159, 159, 159))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcepto1)
                    .addComponent(rbAprobado1)
                    .addComponent(rbNoAprobado1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConcepto2)
                    .addComponent(rbAprobado2)
                    .addComponent(rbNoAprobado2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbIncorecta)
                    .addComponent(rbCorrecta)
                    .addComponent(jLabel2))
                .addGap(4, 4, 4)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbNoAprobado3)
                    .addComponent(rbAprobado3)
                    .addComponent(lblConcepto3))
                .addGap(18, 18, 18)
                .addComponent(lblObservaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        cmbCodigoAnteproyecto.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar Anteproyecto" }));

        lblCodigoAnteproyecto.setText("Codigo Anteproyecto: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegistrarFormatoC)
                                .addGap(93, 93, 93))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCodigoAnteproyecto)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCodigoAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(btnGuardar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistrarFormatoC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbCodigoAnteproyecto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigoAnteproyecto))
                .addGap(36, 36, 36)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar)
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            if (cmbCodigoAnteproyecto.getSelectedIndex() == 0) {
                JOptionPane.showMessageDialog(this, "Debe seleccionar un anteproyecto", "ADVERTENCIA", JOptionPane.INFORMATION_MESSAGE);
            } else {
                atrCO = ClienteDeObjetos.getInstancia();
                FormatoCDTO objFC = new FormatoCDTO();
                objFC.setCodigoAnteproyecto(Long.valueOf(cmbCodigoAnteproyecto.getSelectedItem().toString()));
                objFC.setConcepto1("APROBADO");
                objFC.setConcepto2("APROBADO");
                if (rbCorrecta.isSelected()) {
                    objFC.setEstructura("CORRECTA");
                } else {
                    objFC.setEstructura("INCORRECTA");
                }
                if (rbAprobado3.isSelected()) {
                    objFC.setConceptoDepto("APROBADO");
                } else {
                    objFC.setConceptoDepto("NO APROBADO");
                }
                objFC.setObservaciones(txtObservaciones.getText());
                if (atrCO.getObjRemotoAnteproyectos().registrarFormatoC(objFC)) {
                    JOptionPane.showMessageDialog(this, "Formato Registrado Correctamente", "INFO", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                    atrGuiJefe.setVisible(true);
                    atrGuiJefe.cargarFormatos();
                } else {
                    JOptionPane.showMessageDialog(this, "No se pudo registrar el Formato", "INFO", JOptionPane.INFORMATION_MESSAGE);
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIFC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIFC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.ButtonGroup buttonGroup;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbCodigoAnteproyecto;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCodigoAnteproyecto;
    private javax.swing.JLabel lblConcepto1;
    private javax.swing.JLabel lblConcepto2;
    private javax.swing.JLabel lblConcepto3;
    private javax.swing.JLabel lblObservaciones;
    private javax.swing.JLabel lblRegistrarFormatoC;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JRadioButton rbAprobado1;
    private javax.swing.JRadioButton rbAprobado2;
    private javax.swing.JRadioButton rbAprobado3;
    private javax.swing.JRadioButton rbCorrecta;
    private javax.swing.JRadioButton rbIncorecta;
    private javax.swing.JRadioButton rbNoAprobado1;
    private javax.swing.JRadioButton rbNoAprobado2;
    private javax.swing.JRadioButton rbNoAprobado3;
    private javax.swing.JTextArea txtObservaciones;
    // End of variables declaration//GEN-END:variables
}
