/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.UsuarioDTO;
import cliente.ClienteDeObjetos;
import java.rmi.RemoteException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author juanf
 */
public class GUIFormularioUsuario extends javax.swing.JFrame {

    GUIAdmin atrGUIAdmin;
    ClienteDeObjetos atrCO;
    int atrCreacion = 1;
    boolean banderaActualizar = false;

    /**
     * Creates new form GUICrearUsuario
     */
    public GUIFormularioUsuario() {
        initComponents();
    }

    public GUIFormularioUsuario(GUIAdmin prmGUI, int prmAccion) {
        initComponents();
        atrCreacion = prmAccion;
        atrGUIAdmin = prmGUI;
        if (prmAccion == 1) {
            lblRegistrarUsuario.setText("Registrar Usuario");
            panelMain.setVisible(true);
            btnBuscar.setVisible(false);
            banderaActualizar = false;
        } else if (prmAccion == 2) {
            lblRegistrarUsuario.setText("Actualizar Usuario");
            panelMain.setVisible(false);
            btnBuscar.setVisible(true);
            banderaActualizar = true;
        } else {
            banderaActualizar = false;
            lblRegistrarUsuario.setText("Info Usuario");
            //btnGuardar.setText("Volver");
            panelMain.setVisible(false);
            btnBuscar.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdentificacion = new javax.swing.JLabel();
        txtIdentificacion = new javax.swing.JTextField();
        lblRegistrarUsuario = new javax.swing.JLabel();
        panelMain = new javax.swing.JPanel();
        txtPassword = new javax.swing.JPasswordField();
        txtNombre = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        lblNombre = new javax.swing.JLabel();
        lblRole = new javax.swing.JLabel();
        cmbRole = new javax.swing.JComboBox<>();
        txtDepartamento = new javax.swing.JTextField();
        lblIDepartamento = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblIdentificacion.setText("Identificación:");

        txtIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIdentificacionKeyTyped(evt);
            }
        });

        lblRegistrarUsuario.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblRegistrarUsuario.setText("Registrar Usuario");

        btnGuardar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        lblNombre.setText("Nombre Completo:");

        lblRole.setText("Rol:");

        cmbRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "COORDINADOR", "DIRECTOR", "EVALUADOR", "JEFE DEPARTAMENTO", "DECANO" }));

        lblIDepartamento.setText("Departamento:");

        lblUsuario.setText("Usuario:");

        lblPassword.setText("Contraseña:");

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPassword)
                    .addComponent(lblIDepartamento)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(btnGuardar))
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblRole)
                            .addComponent(lblUsuario))
                        .addGap(18, 18, 18)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombre)
                            .addComponent(txtDepartamento)
                            .addComponent(txtUsuario)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRole)
                    .addComponent(cmbRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDepartamento)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUsuario))
                .addGap(18, 18, 18)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGuardar))
        );

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblIdentificacion)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRegistrarUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnVolver))
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(lblRegistrarUsuario))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnVolver)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdentificacion)
                    .addComponent(txtIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(btnBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            atrCO = ClienteDeObjetos.getInstancia();
            long id = Long.parseLong(txtIdentificacion.getText());
            String nombre = txtNombre.getText();
            String departamento = txtDepartamento.getText();
            String usuario = txtUsuario.getText();
            String password = txtPassword.getText();
            String rol = (String) cmbRole.getSelectedItem();
            UsuarioDTO objUsuario = new UsuarioDTO(id, nombre, rol, departamento, usuario, password);
            if (validarCamposVacios()) {
                if (atrCO.getObjRemotoUsuarios().consultarUsuario(id) != null || atrCO.getObjRemotoUsuarios().existeUsuario(usuario)) {
                    JOptionPane.showMessageDialog(this, "Ya existe un usuario con la información suministrada", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                } else {
                    if (nombre.length() > 65) {
                        JOptionPane.showMessageDialog(this, "El nombre y apellido no puede tener más de 64 caracteres", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
                    } else {
                        if (validar(usuario, "El Usuario ") && validar(password, "La Contraseña ")) {

                            if (atrCreacion == 1) {

                                if (atrCO.getObjRemotoUsuarios().registrarUsuario(objUsuario)) {
                                    JOptionPane.showMessageDialog(this, "Usuario registrado correctamente", "INFO", JOptionPane.INFORMATION_MESSAGE);
                                    this.dispose();
                                } else {
                                    JOptionPane.showMessageDialog(this, "El usuario no se pudo registrar", "ERROR", JOptionPane.ERROR_MESSAGE);
                                }
                            } else if (atrCreacion == 2) {
                                if (atrCO.getObjRemotoUsuarios().modificarUsuario(objUsuario)) {
                                    JOptionPane.showMessageDialog(this, "Usuario Actualizado correctamente", "INFO", JOptionPane.INFORMATION_MESSAGE);
                                }
                            }
                            this.dispose();
                            atrGUIAdmin.mostrarUsuarios();
                        }
                    }
                }
            }
        } catch (RemoteException ex) {
            Logger.getLogger(GUIFormularioUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed
    public boolean validarCamposVacios() {
        if (txtIdentificacion.getText().length() == 0 || txtDepartamento.getText().length() == 0 || txtNombre.getText().length() == 0 || cmbRole.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Se debe diligenciar todos los campos del formulario", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        
        return true;
    }

    public boolean validar(String prmCadena, String credencial) {
        if (prmCadena.length() < 9) {
            JOptionPane.showMessageDialog(this, credencial + " debe de ser de 8 caracteres", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            return false;
        }
        char textoIngresado;

        byte conNumero = 0, conLetra = 0;

        for (byte i = 0; i < prmCadena.length(); i++) {
            textoIngresado = prmCadena.charAt(i);
            String aux = String.valueOf(textoIngresado);

            if (aux.matches("[a-z]") || aux.matches("[A-Z]")) {
                conLetra++;
            } else if (aux.matches("[0-9]")) {
                conNumero++;
            }
        }

        if (conNumero > 0 && conLetra > 0) {
            return true;
        } else {
            JOptionPane.showMessageDialog(this, credencial + " debe de tener numeros y letras", "ADVERTENCIA", JOptionPane.WARNING_MESSAGE);
            return false;
        }

    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed

        try {
            atrCO = ClienteDeObjetos.getInstancia();
            long id = Long.parseLong(txtIdentificacion.getText());
            UsuarioDTO objUsuario = atrCO.getObjRemotoUsuarios().consultarUsuario(id);
            if (objUsuario != null) {
                if (banderaActualizar) {
                    if (objUsuario.getRole() == "ADMIN") {
                        JOptionPane.showMessageDialog(this, "El usuario ingresado es admin por lo que no se puede modificar su información", "INFO", JOptionPane.INFORMATION_MESSAGE);
                    }
                } else {
                    panelMain.setVisible(true);
                    btnBuscar.setVisible(false);
                    txtNombre.setText(objUsuario.getNombreCompleto());
                    cmbRole.setSelectedItem(objUsuario.getRole());
                    txtDepartamento.setText(objUsuario.getDepartamento());
                    txtUsuario.setText(objUsuario.getUsuario());
                    txtPassword.setText(objUsuario.getPassword());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Usuario No Encontrado", "INFO", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        try {
            this.dispose();
            atrGUIAdmin.mostrarUsuarios();
        } catch (RemoteException ex) {
            Logger.getLogger(GUIFormularioUsuario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnVolverActionPerformed

    private void txtIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdentificacionKeyTyped
        char c = evt.getKeyChar();
        if (c < '0' || c > '9') {
            evt.consume();
            //JOptionPane.showMessageDialog(null, "Solo se puede ingresar numeros", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_txtIdentificacionKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cmbRole;
    private javax.swing.JLabel lblIDepartamento;
    private javax.swing.JLabel lblIdentificacion;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistrarUsuario;
    private javax.swing.JLabel lblRole;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPanel panelMain;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtIdentificacion;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
