/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cliente.vistas;

import SGestionAnteproyectos.dto.RegistroDTO;
import SGestionAnteproyectos.dto.UsuarioDTO;
import cliente.ClienteDeObjetos;
import javax.swing.Icon;
import javax.swing.JOptionPane;
import cliente.sop_rmi.*;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author juanf
 */
public class GUIInicioSesion extends javax.swing.JFrame {

    ClienteDeObjetos atrCO;

    /**
     * Creates new form GUIInicioSesion
     */
    public GUIInicioSesion() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        lblIniciarSesion = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnIniciarSesion = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO DE SESION");
        setIconImage(getIconImage());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Contraseña:");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        lblIniciarSesion.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        lblIniciarSesion.setText("Iniciar Sesion");
        jPanel1.add(lblIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, -1, -1));

        lblUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblUsuario.setForeground(new java.awt.Color(255, 255, 255));
        lblUsuario.setText("Usuario:");
        jPanel1.add(lblUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        txtUsuario.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtUsuario.setText("fernando");
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 160, -1));

        txtPassword.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPassword.setText("123321");
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 160, -1));

        btnIniciarSesion.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnIniciarSesion.setText("Iniciar Sesion");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, 150, 30));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondoRUsu.jpg"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        try {
            atrCO = ClienteDeObjetos.getInstancia();
            String varUsuario = txtUsuario.getText();
            String varPassword = txtPassword.getText();
            UsuarioDTO objUsuario = atrCO.getObjRemotoUsuarios().validarUsuario(varUsuario, varPassword);
            if (objUsuario != null) {
                
                switch (objUsuario.getRole()) {
                    case "ADMIN":
                        GUIAdmin objGUIAdmin=new GUIAdmin(this);
                        objGUIAdmin.setVisible(true);
                        this.setVisible(false);
                        break;
                    case "DIRECTOR":
                        GUIDirector objGUIDirector=new GUIDirector(this);
                        DirectorCllbckImpl objRemotoCallback=new DirectorCllbckImpl(objGUIDirector);
                        RegistroDTO objRegistro=new RegistroDTO(-1, objUsuario.getIdentificacion(), objRemotoCallback);
                        atrCO.getObjRemotoAnteproyectos().registrarCallback(objRegistro);
                        objGUIDirector.setVisible(true);
                        this.setVisible(false);
                        break;
                    case "EVALUADOR":
                        GUIEvaluador objGUIEvaluador=new GUIEvaluador(this, objUsuario);
                        objGUIEvaluador.setVisible(true);
                        this.setVisible(false);
                        break;
                    case "JEFE DEPARTAMENTO":
                        GUIJefeDepto objGUIJefeDepto=new GUIJefeDepto(this);
                        objGUIJefeDepto.setVisible(true);
                        this.setVisible(false);
                        break;
                    case "COORDINADOR":
                        GUICoordinador objGUICoordinador=new GUICoordinador(this);
                        objGUICoordinador.setVisible(true);
                        this.setVisible(false);
                        break;
                    case "DECANO":
                        GUIDecano objGUIDecano=new GUIDecano(this);
                        objGUIDecano.setVisible(true);
                        this.setVisible(false);
                        break;
                }
            }else{
               // lblErrorCredenciales.setVisible(true);
                //txtUsuario.setText("");
                //txtPassword.setText("");
                JOptionPane.showMessageDialog(this,"Usuario o contraseña incorrecto","ERROR",JOptionPane.ERROR_MESSAGE);
            }
        } catch (Exception e) {
            System.out.println("Error: "+e.getMessage());
        }

    }//GEN-LAST:event_btnIniciarSesionActionPerformed
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/iconApp.png"));
        return retValue;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIInicioSesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblIniciarSesion;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
