/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SSeguimientoAnteproyectos.vistas;

import SSeguimientoAnteproyectos.ServidorDeObjetos2;
import java.awt.Image;
import java.awt.Toolkit;
import java.rmi.RemoteException;

/**
 *
 * @author Laura
 */
public class GUIConectarServidor2 extends javax.swing.JFrame {
    static GUIConectarServidor2  vistaSeguimiento;
    /**
     * Creates new form GUIConectarServidor2
     */
    public GUIConectarServidor2() {
        initComponents();
         this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTituloCnx2 = new javax.swing.JLabel();
        lblDireccionIp2 = new javax.swing.JLabel();
        txtDireccionIp = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        lblPuerto = new javax.swing.JLabel();
        btnConectarS2 = new javax.swing.JButton();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CONECTAR SERVIDOR DE SEGUIMIENTO");
        setIconImage(getIconImage());
        setPreferredSize(new java.awt.Dimension(425, 370));

        jPanel1.setPreferredSize(new java.awt.Dimension(980, 390));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTituloCnx2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblTituloCnx2.setForeground(new java.awt.Color(204, 204, 204));
        lblTituloCnx2.setText("Conexion Servidor");
        jPanel1.add(lblTituloCnx2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, -1, -1));

        lblDireccionIp2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblDireccionIp2.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionIp2.setText("Cual es el la dirección ip donde se encuentra  el n_s");
        jPanel1.add(lblDireccionIp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, -1));

        txtDireccionIp.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDireccionIp.setText("localhost");
        jPanel1.add(txtDireccionIp, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 227, -1));

        txtPuerto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPuerto.setText("2021");
        jPanel1.add(txtPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 224, -1));

        lblPuerto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPuerto.setForeground(new java.awt.Color(255, 255, 255));
        lblPuerto.setText("Cual es el número de puerto por el cual escucha el n_s");
        jPanel1.add(lblPuerto, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, -1, -1));

        btnConectarS2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnConectarS2.setText("Conectar");
        btnConectarS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarS2ActionPerformed(evt);
            }
        });
        jPanel1.add(btnConectarS2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.png"))); // NOI18N
        jPanel1.add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 420, 350));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarS2ActionPerformed
       String IP=txtDireccionIp.getText();
       int puerto=Integer.parseInt(txtPuerto.getText());
       try{
        ServidorDeObjetos2 SO = new ServidorDeObjetos2(IP,puerto);
        SO.conectar();
        this.dispose();
       }catch(RemoteException ex){
           System.err.println("No fue posible Arrancar el NS o Registrar el objeto remoto" +  ex.getMessage());
       }     
    }//GEN-LAST:event_btnConectarS2ActionPerformed
@Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("recursos/iconApp.png"));
        return retValue;
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarS2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDireccionIp2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblTituloCnx2;
    private javax.swing.JTextField txtDireccionIp;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
