/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SSeguimientoAnteproyectos.vistas;

import SSeguimientoAnteproyectos.ServidorDeObjetos2;
import java.rmi.RemoteException;

/**
 *
 * @author Laura
 */
public class GUIConectarServidor2 extends javax.swing.JFrame {
    static GUIConectarServidor2  vistaSeguimiento;
    /**
     * Creates new form GUIConectarServidor2
     */
    public GUIConectarServidor2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblFondo = new javax.swing.JLabel();
        lblTituloCnx2 = new javax.swing.JLabel();
        lblDireccionIp2 = new javax.swing.JLabel();
        txtDireccionIp = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        lblPuerto = new javax.swing.JLabel();
        btnConectarS2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/fondo.png"))); // NOI18N

        lblTituloCnx2.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        lblTituloCnx2.setForeground(new java.awt.Color(204, 204, 204));
        lblTituloCnx2.setText("Conexion Servidor");

        lblDireccionIp2.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblDireccionIp2.setForeground(new java.awt.Color(255, 255, 255));
        lblDireccionIp2.setText("Cual es el la dirección ip donde se encuentra  el n_s");

        txtDireccionIp.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtDireccionIp.setText("localhost");

        txtPuerto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        txtPuerto.setText("2021");

        lblPuerto.setFont(new java.awt.Font("Yu Gothic UI", 0, 14)); // NOI18N
        lblPuerto.setForeground(new java.awt.Color(255, 255, 255));
        lblPuerto.setText("Cual es el número de puerto por el cual escucha el n_s");

        btnConectarS2.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnConectarS2.setText("Conectar");
        btnConectarS2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConectarS2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(btnConectarS2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(lblTituloCnx2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 77, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblPuerto)
                        .addGap(57, 57, 57))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDireccionIp2)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(txtDireccionIp, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(116, 116, 116))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(lblFondo, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lblTituloCnx2)
                .addGap(34, 34, 34)
                .addComponent(lblDireccionIp2)
                .addGap(32, 32, 32)
                .addComponent(txtDireccionIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblPuerto)
                .addGap(18, 18, 18)
                .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnConectarS2)
                .addContainerGap(52, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lblFondo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 315, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConectarS2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConectarS2ActionPerformed
       String IP=txtDireccionIp.getText();
       int puerto=Integer.parseInt(txtPuerto.getText());
       try{
        ServidorDeObjetos2 SO = new ServidorDeObjetos2(IP,puerto);
        SO.conectar();
        this.dispose();
       }catch(RemoteException ex){
           System.err.println("No fue posible Arrancar el NS o Registrar el objeto remoto" +  ex.getMessage());
       }     
    }//GEN-LAST:event_btnConectarS2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConectarS2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDireccionIp2;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JLabel lblTituloCnx2;
    private javax.swing.JTextField txtDireccionIp;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
